# Generated by Django 4.1.7 on 2023-03-22 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consoles', '0003_alter_shoppingcart_options_remove_console_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Время аренды не может быть меньше 1 дня!')], verbose_name='Время аренды в днях')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_item', to='consoles.console', verbose_name='Приставка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaser', to=settings.AUTH_USER_MODEL, verbose_name='Арендатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-pub_date',),
            },
        ),
    ]
