# Generated by Django 4.1.7 on 2023-03-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(auto_now_add=True, help_text='Укажите дату начала аренды', verbose_name='Начало аренды'),
        ),
    ]
