# Generated by Django 4.1.7 on 2023-03-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_image'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='games.game', verbose_name='Игра')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='rents.rent', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='rent',
            name='games',
            field=models.ManyToManyField(through='rents.GameInRent', to='games.game', verbose_name='Игры'),
        ),
        migrations.AddConstraint(
            model_name='gameinrent',
            constraint=models.UniqueConstraint(fields=('game', 'rent'), name='unique_game_rent'),
        ),
    ]
