# Generated by Django 4.1.7 on 2023-03-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rents', '0001_initial'),
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaser', to=settings.AUTH_USER_MODEL, verbose_name='Арендатель'),
        ),
        migrations.AddField(
            model_name='gameinrent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='games.game', verbose_name='Игра'),
        ),
        migrations.AddField(
            model_name='gameinrent',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='rents.rent', verbose_name='Заказ'),
        ),
        migrations.AddConstraint(
            model_name='gameinrent',
            constraint=models.UniqueConstraint(fields=('game', 'rent'), name='unique_game_rent'),
        ),
    ]
