# Generated by Django 4.1.7 on 2023-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_alter_rent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(auto_now_add=True, help_text='Укажите дату окончание аренды', verbose_name='Конец аренды'),
        ),
    ]
