# Generated by Django 3.2 on 2022-10-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={'verbose_name': 'Консоль', 'verbose_name_plural': 'Консоли'},
        ),
        migrations.AddField(
            model_name='rentalrate',
            name='console',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent.console', verbose_name='Консоль'),
            preserve_default=False,
        ),
    ]
