# Generated by Django 3.2 on 2022-10-21 08:56

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0002_auto_20221018_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='price_five_day',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Стоимость за 5 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_four_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за 4 дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_one_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за 1 день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_prolongation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за продление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_six_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за 6 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_three_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за 3 дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_two_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за 2 дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='price_week_day',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость за неделю'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='console',
            name='description',
            field=models.TextField(verbose_name='Штрих-код'),
        ),
        migrations.AlterField(
            model_name='console',
            name='status',
            field=models.CharField(blank=True, choices=[('F', 'Свободно'), ('R', 'Арендовано')], default='F', max_length=1, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='console',
            field=models.ForeignKey(help_text='Выберите приставку', null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.console', verbose_name='Приставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 10, 21), help_text='Укажите начало даты аренды', verbose_name='Дата начало аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=datetime.date(2022, 10, 21), help_text='Укажите окончание даты аренды', verbose_name='Дата окончание аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
