# Generated by Django 3.2 on 2022-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrate',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость'),
        ),
    ]
