# Generated by Django 3.2 on 2022-10-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20221017_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrate',
            options={'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
        migrations.RemoveField(
            model_name='rentalrate',
            name='console',
        ),
        migrations.RemoveField(
            model_name='rentalrate',
            name='cost',
        ),
        migrations.AlterField(
            model_name='order',
            name='console',
            field=models.ForeignKey(blank=True, help_text='Выберите приставку', null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.console', verbose_name='Приставка'),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.console', verbose_name='Консоль')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rentalrate', verbose_name='Срок арендной платы')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent.cost', verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
