# Generated by Django 3.2 on 2022-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20221017_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='status',
            field=models.CharField(choices=[('F', 'Свободно'), ('R', 'Арендовано')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
