# Generated by Django 4.1.7 on 2023-03-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_shoppinglist_favoritegame_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shopping_list_games', 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
    ]
