# Generated by Django 4.1.7 on 2023-03-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_shoppinglist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default=1, upload_to='games/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
