# Generated by Django 4.1.7 on 2023-03-22 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0003_alter_shoppingcart_options_remove_console_status'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRentConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Время аренды не может быть меньше 1 дня!')], verbose_name='Количество дней аренды')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_rent', to='consoles.console', verbose_name='Приставка')),
                ('time_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_rent', to='rent.timerent', verbose_name='Период')),
            ],
        ),
    ]
