# Generated by Django 4.1.7 on 2023-03-22 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0005_alter_shoppinglist_options'),
        ('consoles', '0003_alter_shoppingcart_options_remove_console_status'),
        ('rent', '0002_timerentconsole'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesInRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Игра в заказе',
                'verbose_name_plural': 'Игры в заказе',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Время аренды не может быть меньше 1 дня!')], verbose_name='Время аренды в днях')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_item', to='consoles.console', verbose_name='Приставка')),
                ('games', models.ManyToManyField(related_name='games_in_rent', through='rent.GamesInRent', to='games.game', verbose_name='Игры')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaser', to=settings.AUTH_USER_MODEL, verbose_name='Арендатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-pub_date',),
                'default_related_name': 'recipes',
            },
        ),
        migrations.RemoveField(
            model_name='timerentconsole',
            name='console',
        ),
        migrations.RemoveField(
            model_name='timerentconsole',
            name='time_rent',
        ),
        migrations.DeleteModel(
            name='TimeRent',
        ),
        migrations.DeleteModel(
            name='TimeRentConsole',
        ),
        migrations.AddField(
            model_name='gamesinrent',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='rent.rent', verbose_name='Заказ'),
        ),
        migrations.AddConstraint(
            model_name='rent',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_for_author'),
        ),
        migrations.AddConstraint(
            model_name='gamesinrent',
            constraint=models.UniqueConstraint(fields=('rent', 'game'), name='unique_rent_game'),
        ),
    ]
