# Generated by Django 4.1.7 on 2023-03-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_gamesinrent_rent_remove_timerentconsole_console_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveConstraint(
            model_name='rent',
            name='unique_for_author',
        ),
    ]
