# Generated by Django 4.1.7 on 2023-04-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_genre_game_genres'),
        ('blog', '0002_comment_genre_review_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Укажите игру', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game', verbose_name='Игра'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
