# Generated by Django 4.1.7 on 2023-04-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Укажите игру', null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра'),
        ),
    ]
