# Generated by Django 4.1.7 on 2023-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_author_post'),
        ),
    ]
