# Generated by Django 4.1.7 on 2023-04-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_genre_options'),
        ('blog', '0006_post_unique_author_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(default=1, help_text='Укажите игру', on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра'),
            preserve_default=False,
        ),
    ]
