# Generated by Django 4.1.7 on 2023-04-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
