# Generated by Django 4.1.7 on 2023-05-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
