# Generated by Django 4.1.7 on 2023-05-05 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCountPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('viewed_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ('-viewed_on',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='viewcountpost',
            index=models.Index(fields=['-viewed_on'], name='blog_viewco_viewed__398448_idx'),
        ),
    ]
