# Generated by Django 4.1.7 on 2023-05-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_viewcountpost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCountPost',
        ),
    ]
