# Generated by Django 4.1.7 on 2023-03-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименовение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('barcode', models.TextField(verbose_name='Штрих-код')),
                ('status', models.CharField(blank=True, choices=[('free', 'Свободно'), ('rent', 'Арендовано')], default='free', max_length=4, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Консоль',
                'verbose_name_plural': 'Консоли',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименовение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('multu_user', models.BooleanField(default=False, verbose_name='Многопользовательская')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='console',
            constraint=models.UniqueConstraint(fields=('title', 'barcode'), name='unique_title_barcode'),
        ),
    ]
