# Generated by Django 4.1.7 on 2023-03-21 05:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RemoveConstraint(
            model_name='console',
            name='unique_title_barcode',
        ),
        migrations.RenameField(
            model_name='console',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='console',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consoles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='console',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='URL'),
        ),
        migrations.AddConstraint(
            model_name='console',
            constraint=models.UniqueConstraint(fields=('name', 'barcode'), name='unique_name_barcode'),
        ),
    ]
