# Generated by Django 4.1.7 on 2023-04-05 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consoles', '0001_initial'),
        ('core', '0002_likedislike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='review',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.console', verbose_name='Игровая приставка'),
        ),
        migrations.AddField(
            model_name='rentalprice',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_price', to='consoles.console', verbose_name='Игровая консколь'),
        ),
        migrations.AddField(
            model_name='rentalprice',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_price', to='core.period', verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.console', verbose_name='Игровая приставка'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='console',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендодатель'),
        ),
        migrations.AddField(
            model_name='console',
            name='categories',
            field=models.ManyToManyField(to='consoles.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='console',
            name='timeframe',
            field=models.ManyToManyField(through='consoles.RentalPrice', to='core.period', verbose_name='Стоимость аренды'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'console'), name='unique_shopping'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('console', 'author'), name='unique_review_console'),
        ),
        migrations.AddConstraint(
            model_name='rentalprice',
            constraint=models.UniqueConstraint(fields=('period', 'console'), name='unique_period_console'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'console'), name='unique_user_console'),
        ),
        migrations.AddConstraint(
            model_name='console',
            constraint=models.UniqueConstraint(fields=('name', 'barcode'), name='unique_name_console'),
        ),
    ]
