# Generated by Django 4.1.7 on 2023-03-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_list', 'verbose_name': 'Бронь', 'verbose_name_plural': 'Бронь'},
        ),
        migrations.RemoveField(
            model_name='console',
            name='status',
        ),
    ]
