# Generated by Django 4.1.7 on 2023-03-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('consoles', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='console',
            name='album',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='core.imagealbum'),
            preserve_default=False,
        ),
    ]
