# Generated by Django 4.1.7 on 2023-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0003_like_dislike_like_unique_like_dislike_unique_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(help_text='Введите текст', max_length=256, verbose_name='Текст'),
        ),
    ]
