# Generated by Django 4.1.7 on 2023-03-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0003_alter_shoppingcart_options_remove_console_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={'verbose_name': 'Игровая приставка', 'verbose_name_plural': 'Игровые приставки'},
        ),
        migrations.AlterField(
            model_name='console',
            name='image',
            field=models.ImageField(default=1, upload_to='consoles/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
