# Generated by Django 4.1.7 on 2023-03-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('consoles', '0003_delete_image_console_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='album',
        ),
        migrations.CreateModel(
            name='ImagesInConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_images', to='consoles.console', verbose_name='Приставка')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_images', to='core.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения ',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='console',
            name='images',
            field=models.ManyToManyField(through='consoles.ImagesInConsole', to='core.image', verbose_name='Изображения'),
        ),
        migrations.AddConstraint(
            model_name='imagesinconsole',
            constraint=models.UniqueConstraint(fields=('console', 'image'), name='unique_console_image'),
        ),
    ]
