# Generated by Django 4.1.7 on 2023-03-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0005_category_alter_console_options_console_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='slug',
        ),
    ]
