# Generated by Django 4.1.7 on 2023-03-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consoles', '0006_remove_console_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='console',
            old_name='category',
            new_name='categories',
        ),
    ]
