# Generated by Django 4.1.7 on 2023-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, help_text='Наличие аватара увеличивает к вам доверие', upload_to='', verbose_name='Аватар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, help_text='Необходимо указать номер телефона', max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Пользователь', 'Пользователь'), ('Арендодатель', 'Арендодатель')], default='Пользователь', max_length=12, verbose_name='Роль'),
        ),
    ]
