# Generated by Django 4.1.7 on 2023-05-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_seen_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
    ]
