# Generated by Django 4.1.7 on 2023-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название периода', max_length=50, unique=True, verbose_name='Название')),
                ('value', models.PositiveSmallIntegerField(help_text='Задайте значение периода', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Период аренды',
                'verbose_name_plural': 'Периоды аренды',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='unique_period'),
        ),
    ]
