# Generated by Django 4.1.7 on 2023-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='Задайте количество дней', verbose_name='Количество дней'),
        ),
    ]
