# Generated by Django 4.1.7 on 2023-05-03 05:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=100, validators=[core.validators.validate_not_empty], verbose_name='Имя')),
                ('email', models.EmailField(help_text='Оставьте своё сообщение', max_length=254, validators=[core.validators.validate_not_empty], verbose_name='Электронный адрес (email)')),
                ('phone', models.IntegerField(help_text='Оставьте свой телефон', verbose_name='Номер телефона')),
                ('body', models.TextField(validators=[core.validators.validate_not_empty], verbose_name='Содержимое письма')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-time_create'],
            },
        ),
    ]
