# Generated by Django 4.1.7 on 2023-05-03 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP отправителя'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
