# Generated by Django 4.1.7 on 2023-05-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_viewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
