name: RentPlay Workflows

on:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort pytest-local-badge
        pip install -r backend/requirements.txt

    - name: Test with flake8
      run: |
        python -m flake8
  
    - name: Run tests with pytest
      run: |
        pytest --cov=./backend/ --cov-report=xml --local-badge-output-dir badges/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: pytest
        name: rentplay-pytest-cov
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
